import { useState } from 'react';
import { FileText, Info, Shield, Printer, Copy, Check } from 'lucide-react';
import { format } from 'date-fns';
import EvidenceReference from './EvidenceReference';

export default function ForensicReportView({ report }) {
  const [copied, setCopied] = useState(false);

  if (!report) return null;

  const {
    deterministicSummary,
    aiFindings,
    limitations,
    generatedAt,
    reportVersion
  } = report;

  const verdict = deterministicSummary?.verdict || {};

  const handleCopySummary = async () => {
    try {
      const summaryText = [
        `DETECTIQ FORENSIC INVESTIGATION REPORT (v${reportVersion}.0)`,
        `Generated: ${format(new Date(generatedAt), 'PPP p')}`,
        `Classification: ${verdict.classification?.toUpperCase() || 'UNKNOWN'}`,
        `Risk Score: ${verdict.riskScore ?? 0}/100 (${verdict.riskLevel?.toUpperCase() || 'UNKNOWN'})`,
        `Confidence: ${verdict.confidence >= 80 ? 'High' : verdict.confidence >= 50 ? 'Moderate' : 'Limited'}`,
        '',
        '--- EXECUTIVE SUMMARY ---',
        aiFindings?.summary || 'Deterministic analysis executed without supplementary LLM summary.',
        '',
        '--- KEY FINDINGS ---',
        ...(aiFindings?.keyFindings?.map(f => `• [${f.severity?.toUpperCase()}] ${f.title}: ${f.description}`) || ['• Deterministic forensic indicators verified.']),
        '',
        'Generated by DetectIQ Automated Threat Analysis Engine'
      ].join('\n');

      await navigator.clipboard.writeText(summaryText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy summary to clipboard', err);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="bg-card rounded-xl border border-border shadow-xl overflow-hidden text-sm print:bg-white print:text-black print:border-none print:shadow-none print:m-0">
      
      {/* Print-Only Header Banner */}
      <div className="hidden print:block p-6 border-b-2 border-black mb-6">
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-black font-mono">DETECTIQ FORENSIC INVESTIGATION REPORT</h1>
            <p className="text-xs text-gray-600 mt-1">Classification: CONFIDENTIAL // SOC INCIDENT AUDIT</p>
          </div>
          <div className="text-right text-xs font-mono">
            <div>VERSION: v{reportVersion}.0</div>
            <div>DATE: {format(new Date(generatedAt), 'yyyy-MM-dd HH:mm:ss')}</div>
          </div>
        </div>
      </div>

      {/* Screen Interactive Header */}
      <div className="bg-secondary p-6 border-b border-border print:hidden">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-4">
          <div className="flex items-center gap-3">
            <div className="p-2.5 bg-accent-blue/20 text-accent-blue rounded-lg">
              <FileText size={24} />
            </div>
            <div>
              <h2 className="text-xl font-bold text-primary">Forensic Investigation Report</h2>
              <p className="text-muted mt-1">Generated {format(new Date(generatedAt), 'PPP p')}</p>
            </div>
          </div>
          <div className="flex items-center gap-2.5">
            <span className="inline-block px-3 py-1 bg-secondary/80 text-secondary border border-border rounded-full text-xs font-medium mr-2">
              v{reportVersion}.0
            </span>
            <button
              onClick={handleCopySummary}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-card border border-border text-secondary hover:text-primary text-xs font-semibold shadow-sm transition-colors cursor-pointer"
              title="Copy executive briefing text"
            >
              {copied ? <Check size={14} className="text-success" /> : <Copy size={14} />}
              <span>{copied ? 'Copied' : 'Copy Text'}</span>
            </button>
            <button
              onClick={handlePrint}
              className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg bg-primary text-background hover:opacity-90 text-xs font-bold shadow-soft transition-all cursor-pointer"
              title="Print or export as PDF dossier"
            >
              <Printer size={14} />
              <span>Print / PDF</span>
            </button>
          </div>
        </div>
      </div>

      <div className="p-6 space-y-8 print:p-0 print:space-y-6">
        {/* Detection Verdict */}
        <section>
          <h3 className="text-lg font-semibold text-primary mb-4 border-b border-border pb-2 print:text-black print:border-black">
            1. Detection Verdict
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="bg-secondary/50 p-4 rounded-lg border border-border print:bg-gray-100 print:border-gray-300">
              <p className="text-muted text-xs uppercase tracking-wider mb-1 print:text-gray-700">Classification</p>
              <p className="text-lg font-semibold font-mono text-primary capitalize print:text-black">{verdict.classification}</p>
            </div>
            <div className="bg-secondary/50 p-4 rounded-lg border border-border print:bg-gray-100 print:border-gray-300">
              <p className="text-muted text-xs uppercase tracking-wider mb-1 print:text-gray-700">Risk Score</p>
              <div className="flex items-center gap-2">
                <p className="text-lg font-semibold font-mono text-primary print:text-black">{verdict.riskScore}/100</p>
                <span className={`px-2 py-0.5 rounded text-[10px] uppercase font-bold ${
                  verdict.riskLevel === 'critical' || verdict.riskLevel === 'high' ? 'bg-danger/20 text-danger border border-danger/30' :
                  verdict.riskLevel === 'medium' ? 'bg-warning/20 text-warning border border-warning/30' :
                  'bg-success/20 text-success border border-success/30'
                }`}>
                  {verdict.riskLevel}
                </span>
              </div>
            </div>
            <div className="bg-secondary/50 p-4 rounded-lg border border-border print:bg-gray-100 print:border-gray-300">
              <p className="text-muted text-xs uppercase tracking-wider mb-1 print:text-gray-700">Assessment Strength</p>
              <p className="text-lg font-semibold font-mono text-primary print:text-black">
                {verdict.confidence >= 80 ? 'High' : verdict.confidence >= 50 ? 'Moderate' : 'Limited'}
              </p>
            </div>
          </div>
        </section>

        {/* Registration Intelligence */}
        {deterministicSummary?.registrationIntelligence && (
          <section>
            <h3 className="text-lg font-semibold text-primary mb-4 border-b border-border pb-2 flex items-center gap-2 print:text-black print:border-black">
              Registration Intelligence
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              {deterministicSummary.registrationIntelligence.registrar && (
                <div className="bg-secondary/50 p-4 rounded-lg border border-border print:bg-gray-100 print:border-gray-300">
                  <p className="text-muted text-xs uppercase tracking-wider mb-1 print:text-gray-700">Registrar</p>
                  <p className="font-semibold text-primary print:text-black">{deterministicSummary.registrationIntelligence.registrar}</p>
                </div>
              )}
              {deterministicSummary.registrationIntelligence.createdAt && (
                <div className="bg-secondary/50 p-4 rounded-lg border border-border print:bg-gray-100 print:border-gray-300">
                  <p className="text-muted text-xs uppercase tracking-wider mb-1 print:text-gray-700">Created</p>
                  <p className="font-semibold text-primary print:text-black">{format(new Date(deterministicSummary.registrationIntelligence.createdAt), 'MMM d, yyyy')}</p>
                </div>
              )}
              {deterministicSummary.registrationIntelligence.registrationAgeDays !== null && (
                <div className="bg-secondary/50 p-4 rounded-lg border border-border print:bg-gray-100 print:border-gray-300">
                  <p className="text-muted text-xs uppercase tracking-wider mb-1 print:text-gray-700">Registration Age</p>
                  <p className="font-semibold text-primary print:text-black">{deterministicSummary.registrationIntelligence.registrationAgeDays} days</p>
                </div>
              )}
              {deterministicSummary.registrationIntelligence.expiresAt && (
                <div className="bg-secondary/50 p-4 rounded-lg border border-border print:bg-gray-100 print:border-gray-300">
                  <p className="text-muted text-xs uppercase tracking-wider mb-1 print:text-gray-700">Expires</p>
                  <p className="font-semibold text-primary print:text-black">{format(new Date(deterministicSummary.registrationIntelligence.expiresAt), 'MMM d, yyyy')}</p>
                </div>
              )}
            </div>
            
            {(deterministicSummary.registrationIntelligence.statuses?.length > 0 || deterministicSummary.registrationIntelligence.nameservers?.length > 0) && (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                {deterministicSummary.registrationIntelligence.statuses?.length > 0 && (
                  <div className="bg-secondary/50 p-4 rounded-lg border border-border print:bg-gray-100 print:border-gray-300">
                    <p className="text-muted text-xs uppercase tracking-wider mb-2 print:text-gray-700">Domain Statuses</p>
                    <div className="flex flex-wrap gap-2">
                      {deterministicSummary.registrationIntelligence.statuses.map((status, idx) => (
                        <span key={idx} className="px-2 py-1 bg-secondary text-[11px] rounded border border-border print:bg-white print:border-gray-400">
                          {status}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
                {deterministicSummary.registrationIntelligence.nameservers?.length > 0 && (
                  <div className="bg-secondary/50 p-4 rounded-lg border border-border print:bg-gray-100 print:border-gray-300">
                    <p className="text-muted text-xs uppercase tracking-wider mb-2 print:text-gray-700">Nameservers</p>
                    <div className="flex flex-col gap-1">
                      {deterministicSummary.registrationIntelligence.nameservers.map((ns, idx) => (
                        <span key={idx} className="text-sm font-mono text-secondary print:text-black">
                          {ns}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}
            <div className="text-right mt-2 print:hidden">
              <span className="text-xs text-muted">Source: {deterministicSummary.registrationIntelligence.rdapServer || 'RDAP'}</span>
            </div>
          </section>
        )}

        {/* AI Findings */}
        {aiFindings ? (
          <section>
            <h3 className="text-lg font-semibold text-primary mb-4 border-b border-border pb-2 flex items-center gap-2 print:text-black print:border-black">
              <Shield size={18} className="text-accent-violet print:text-black" />
              2. AI Copilot Analysis
            </h3>
            
            <div className="space-y-6">
              <div className="bg-accent-violet/5 p-4 rounded-lg border border-accent-violet/20 print:bg-gray-100 print:border-gray-300">
                <h4 className="font-medium text-accent-violet mb-2 print:text-black">Executive Summary</h4>
                <p className="text-secondary leading-relaxed print:text-black">{aiFindings.summary}</p>
              </div>

              {aiFindings.keyFindings?.length > 0 && (
                <div>
                  <h4 className="font-medium text-primary mb-3 print:text-black">Key Findings</h4>
                  <div className="grid gap-3">
                    {aiFindings.keyFindings.map((finding, idx) => (
                      <div key={idx} className="bg-secondary/50 p-4 rounded-lg border border-border print:bg-gray-100 print:border-gray-300">
                        <div className="flex items-start justify-between gap-4">
                          <div>
                            <p className="font-medium text-primary print:text-black">{finding.title}</p>
                            <p className="text-muted mt-1 print:text-gray-700">{finding.description}</p>
                          </div>
                          <span className={`shrink-0 px-2 py-1 rounded text-[10px] uppercase font-bold ${
                            finding.severity === 'critical' ? 'bg-danger/20 text-danger' :
                            finding.severity === 'high' ? 'bg-warning/20 text-warning' :
                            finding.severity === 'medium' ? 'bg-warning/20 text-warning' :
                            'bg-accent-blue/20 text-accent-blue'
                          }`}>
                            {finding.severity}
                          </span>
                        </div>
                        {finding.evidenceIds?.length > 0 && (
                          <div className="mt-3 pt-3 border-t border-border/50 flex flex-wrap gap-2 print:hidden">
                            {finding.evidenceIds.map(id => (
                              <EvidenceReference key={id} investigationId={report.investigationId} evidenceId={id} />
                            ))}
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </section>
        ) : (
          <section>
            <h3 className="text-lg font-semibold text-primary mb-4 border-b border-border pb-2 print:text-black print:border-black">2. AI Copilot Analysis</h3>
            <div className="bg-secondary/50 p-4 rounded-lg border border-border text-center text-muted">
              AI insights are currently unavailable for this report.
            </div>
          </section>
        )}

        {/* Limitations */}
        {limitations?.length > 0 && (
          <section>
            <h3 className="text-lg font-semibold text-primary mb-4 border-b border-border pb-2 flex items-center gap-2 print:text-black print:border-black">
              <Info size={18} className="text-muted print:text-black" />
              3. Evidence Limitations
            </h3>
            <div className="bg-secondary/50 p-4 rounded-lg border border-border print:bg-gray-100 print:border-gray-300">
              <ul className="list-disc list-inside space-y-2 text-secondary print:text-black">
                {limitations.map((lim, idx) => (
                  <li key={idx}>{lim}</li>
                ))}
              </ul>
            </div>
          </section>
        )}
      </div>
    </div>
  );
}
